from dotenv import load_dotenv
import os

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL", "mysql+pymysql://smart:smart123456@127.0.0.1:3307/smart_home?charset=utf8mb4")
MQTT_BROKER = os.getenv("MQTT_BROKER", "localhost")
MQTT_PORT = int(os.getenv("MQTT_PORT", "1883"))
TOPIC_SUFFIX = os.getenv("TOPIC_SUFFIX", "sh7k2d")
FACE_THRESHOLD = float(os.getenv("FACE_THRESHOLD", "0.40"))
SERVERCHAN_KEY = os.getenv("SERVERCHAN_KEY", "")
FAN_AUTO_ON_TEMP = float(os.getenv("FAN_AUTO_ON_TEMP", "30"))
FAN_AUTO_OFF_TEMP = float(os.getenv("FAN_AUTO_OFF_TEMP", "28"))
SERIAL_PORT = os.getenv("SERIAL_PORT", "auto")
SERIAL_BAUD = int(os.getenv("SERIAL_BAUD", "9600"))
BACKEND_URL = os.getenv("BACKEND_URL", "http://localhost:8000")
DOOR_AUTO_CLOSE_SEC = int(os.getenv("DOOR_AUTO_CLOSE_SEC", "4"))
LINKAGE_CLASS = os.getenv("LINKAGE_CLASS", "traffic light")
YOLO_MODEL_PATH = os.getenv("YOLO_MODEL_PATH", "models/best.pt")
INSIGHTFACE_ROOT = os.getenv("INSIGHTFACE_ROOT", "models/insightface")
INSIGHTFACE_NAME = os.getenv("INSIGHTFACE_NAME", "buffalo_l")
API_KEY = os.getenv("API_KEY", "")
CAPTURE_DEVICE = int(os.getenv("CAPTURE_DEVICE", "0"))
CAMERA_EXPOSURE = float(os.getenv("CAMERA_EXPOSURE", "0.25"))
CAMERA_BRIGHTNESS = float(os.getenv("CAMERA_BRIGHTNESS", "128"))
CAMERA_AUTO_EXPOSURE = float(os.getenv("CAMERA_AUTO_EXPOSURE", "0.75"))
CAMERA_AUTO_WB = float(os.getenv("CAMERA_AUTO_WB", "0"))
CAMERA_WB_TEMP = float(os.getenv("CAMERA_WB_TEMP", "4500"))
CAMERA_GAMMA = float(os.getenv("CAMERA_GAMMA", "1.35"))
CAMERA_WARMTH = int(os.getenv("CAMERA_WARMTH", "14"))
CAMERA_CONTRAST = float(os.getenv("CAMERA_CONTRAST", "1.3"))
CORS_ORIGINS = [o.strip() for o in os.getenv("CORS_ORIGINS", "http://localhost:5173,http://localhost:3000").split(",") if o.strip()]
