CREATE DATABASE IF NOT EXISTS smart_home CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'smart'@'%' IDENTIFIED BY 'smart123456';
GRANT ALL PRIVILEGES ON smart_home.* TO 'smart'@'%';
FLUSH PRIVILEGES;
